---
shows:
  The Walking Dead:
  Game of thrones:
    org_template: "** Game of Thrones <%U>"
  The Big Bang Theory:
    alt_name: "TBBT"
org_template: "** <%U> %n S%SE%E %T"
days_until_next_check: 15
days_preceding: 7
