#! /bin/bash -

SCRIPT_NAME=`basename $0`
USER=sylvain

mkdir -p "/home/$USER/deathrow/logs"
DATE=$(date "+%Y-%m-%d_%H:%M:%S")
LOG="/home/$USER/deathrow/logs/$SCRIPT_NAME-$DATE.log"

exec >$LOG 2>&1

echo "[$(date)] $SCRIPT_NAME starting..."

# No need to bash -c the command
sudo -u $USER -s bash -c "ruby ~/Dropbox/projects/TVrage2org/main.rb -f ~/.config/TVrage2org/config.yaml -o ~/Dropbox/Org/series.org -d debug"

echo "[$(date)] $SCRIPT_NAME done."
